Update .gitea/workflows/create_image.yaml

diff --git a/.gitea/workflows/create_image.yaml b/.gitea/workflows/create_image.yaml
--- a/.gitea/workflows/create_image.yaml
+++ b/.gitea/workflows/create_image.yaml
@@ -51,10 +51,6 @@ jobs:
           username: ${{ secrets.ACTION_USERNAME }}
           password: ${{ secrets.ACTION_PASSWORD }}
 
-      # - name: Deploy
-      #   run: |
-      #     docker build -t gitea.kripso-world.com/${{ gitea.repository }}:latest .
-      #     docker push gitea.kripso-world.com/${{ gitea.repository }}
       - name: Build and push Docker image
         uses: docker/build-push-action@v6
         with:
@@ -65,3 +61,22 @@ jobs:
           tags: |
             gitea.kripso-world.com/${{ gitea.repository }}:latest
             gitea.kripso-world.com/${{ gitea.repository }}:${{ gitea.sha }}
+
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install -y jq
+
+      - name: Inspect pushed image digests
+        id: inspect
+        run: |
+          LATEST_DIGEST=$(docker buildx imagetools inspect gitea.kripso-world.com/${{ gitea.repository }}:latest --format '{{json .}}' | jq -r '.manifest.digest')
+          SHA_DIGEST=$(docker buildx imagetools inspect gitea.kripso-world.com/${{ gitea.repository }}:${{ gitea.sha }} --format '{{json .}}' | jq -r '.manifest.digest')
+
+          echo "Latest digest: $LATEST_DIGEST"
+          echo "Commit digest: $SHA_DIGEST"
+
+          if [ "$LATEST_DIGEST" != "$SHA_DIGEST" ]; then
+            echo "❌ ERROR: latest does not match the commit digest"
+            exit 1
+          else
+            echo "✅ latest tag matches the commit image"
+          fi
