Update .gitea/workflows/create_dev_image.yaml

diff --git a/.gitea/workflows/create_dev_image.yaml b/.gitea/workflows/create_dev_image.yaml
--- a/.gitea/workflows/create_dev_image.yaml
+++ b/.gitea/workflows/create_dev_image.yaml
@@ -1,61 +1,61 @@
 name: Docker Build and Push Dev
 
-on:
-  push:
-    branches:
-      - dev*
-      - dev/**
-  pull_request:
-    branches:
-      - dev*
-      - dev/**
-      - master
+# on:
+#   push:
+#     branches:
+#       - dev*
+#       - dev/**
+#   pull_request:
+#     branches:
+#       - dev*
+#       - dev/**
+#       - master
 
-jobs:
-  build-and-push-dev:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out repository code
-        uses: actions/checkout@v4
+# jobs:
+#   build-and-push-dev:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Check out repository code
+#         uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        with:
-          create: true
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v3
+#         with:
+#           create: true
 
-      - name: Login to Gitea Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: gitea.kripso-world.com
-          username: ${{ secrets.ACTION_USERNAME }}
-          password: ${{ secrets.ACTION_PASSWORD }}
+#       - name: Login to Gitea Container Registry
+#         uses: docker/login-action@v3
+#         with:
+#           registry: gitea.kripso-world.com
+#           username: ${{ secrets.ACTION_USERNAME }}
+#           password: ${{ secrets.ACTION_PASSWORD }}
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          push: true
-          no-cache: true
-          platforms: linux/amd64,linux/arm64
-          tags: |
-            gitea.kripso-world.com/${{ gitea.repository }}:dev
-            gitea.kripso-world.com/${{ gitea.repository }}:${{ gitea.sha }}
+#       - name: Build and push Docker image
+#         uses: docker/build-push-action@v6
+#         with:
+#           context: .
+#           push: true
+#           no-cache: true
+#           platforms: linux/amd64,linux/arm64
+#           tags: |
+#             gitea.kripso-world.com/${{ gitea.repository }}:dev
+#             gitea.kripso-world.com/${{ gitea.repository }}:${{ gitea.sha }}
 
-      - name: Install jq
-        run: sudo apt-get update && sudo apt-get install -y jq
+#       - name: Install jq
+#         run: sudo apt-get update && sudo apt-get install -y jq
 
-      - name: Inspect pushed image digests
-        id: inspect
-        run: |
-          DEV_DIGEST=$(docker buildx imagetools inspect gitea.kripso-world.com/${{ gitea.repository }}:dev --format '{{json .}}' | jq -r '.manifest.digest')
-          SHA_DIGEST=$(docker buildx imagetools inspect gitea.kripso-world.com/${{ gitea.repository }}:${{ gitea.sha }} --format '{{json .}}' | jq -r '.manifest.digest')
+#       - name: Inspect pushed image digests
+#         id: inspect
+#         run: |
+#           DEV_DIGEST=$(docker buildx imagetools inspect gitea.kripso-world.com/${{ gitea.repository }}:dev --format '{{json .}}' | jq -r '.manifest.digest')
+#           SHA_DIGEST=$(docker buildx imagetools inspect gitea.kripso-world.com/${{ gitea.repository }}:${{ gitea.sha }} --format '{{json .}}' | jq -r '.manifest.digest')
 
-          echo "Latest digest: $DEV_DIGEST"
-          echo "sha digest: $SHA_DIGEST"
+#           echo "Latest digest: $DEV_DIGEST"
+#           echo "sha digest: $SHA_DIGEST"
 
-          if [ "$DEV_DIGEST" != "$SHA_DIGEST" ]; then
-            echo "❌ ERROR: latest does not match the sha digest"
-            exit 1
-          else
-            echo "✅ latest tag matches the sha image"
-          fi
+#           if [ "$DEV_DIGEST" != "$SHA_DIGEST" ]; then
+#             echo "❌ ERROR: latest does not match the sha digest"
+#             exit 1
+#           else
+#             echo "✅ latest tag matches the sha image"
+#           fi
